export const SWIPABLE_BUTTON = 60;
export const SWIPABLE_WIDTH = 350;
export const SWIPABLE_PADDING = 8;
export const SWIPABLE_HEIGHT = 70;

export const SWIPABLE_AREA = SWIPABLE_HEIGHT - 2* SWIPABLE_PADDING;
export const SWIPABLE_RANGE = SWIPABLE_WIDTH - 2* SWIPABLE_PADDING - SWIPABLE_AREA;